name: Deploy 🚀

on:
  push:
    branches: ["master", "deploy-test"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v2
      - run: mkdir gh-pages
      - run: npm install --production
      - run: BASE_URL="/blog" npm run -s build
      - uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: gh-pages
