name: Deploy 🚀

on:
  push:
    branches: ["master", "deploy-test"]
  issue_comment:
    # redeploy when new comments are left

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p gh-pages
      - run: npm install --omit=dev
      - run: "./node_modules/.bin/ts-node ./generate-content-for-comments.ts > ${{github.workspace}}/site.json"
      - uses: ./.github/actions/issue-comments
        with:
          content-path: "${{github.workspace}}/site.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: BASE_URL="/" npm run -s build
      - uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: gh-pages
