name: Deploy 🚀

on:
  push:
    branches: ["master", "deploy-test"]
  issue_comment:
    # redeploy when new comments are left

# avoid creating duplicate issues
concurrency: deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p gh-pages
      - run: npm install --omit=dev
      - run: "./node_modules/.bin/ts-node ./generate-content-for-comments.ts > ${{github.workspace}}/site.json"
      - uses: ./.github/actions/issue-comments
        with:
          content-path: "${{github.workspace}}/site.json"
          output-path: "${{github.workspace}}/comments"
        env:
          GITHUB_TOKEN: ${{ secrets.COMMENT_API_TOKEN }}
      - run: ls "${{github.workspace}}/comments"
      - run: npm run -s build
        env:
          COMMENT_PATH: "${{github.workspace}}/comments"
          BASE_URL: "/"
      - uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: gh-pages
